### ISSUE TITLE
Question + README issue: pngjs or node-png

### ISSUE THREAD

**Issue by zavelevsky** [leogiese/node-png#3]
README file example shows: require('pngjs') instead of require('node-png').

Leads me to a question: I'm looking for a maintained fork of pngjs with support to newer node versions. Do you plan for this fork to be that - or are you planning API changes? If I've been using PNGJS can I simply switch over to you?

Was the code tested on current node version?

Thanks!

**Comment by leogiese** [comment]
@zavelevsky  thanks, updated README , and  please use `node-png`
